import "../styles/globals.css";
import type { AppProps } from "next/app";
import WalletProvider from "../context/walletContextProvider";
import { Web3ReactProvider } from "@web3-react/core";
import {
  ExternalProvider,
  JsonRpcFetchFunc,
  Web3Provider,
} from "@ethersproject/providers";
import { QueryClient, QueryClientProvider } from "react-query";
import Head from "next/head";

const getLibrary = (
  provider: ExternalProvider | JsonRpcFetchFunc
): Web3Provider => {
  const library = new Web3Provider(provider);
  library.pollingInterval = 12000;
  return library;
};

const queryClient = new QueryClient();

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          media="screen"
          href="http://fonts.googleapis.com/css?family=Press+Start+2P"
          type="text/css"
        />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Web3ReactProvider getLibrary={getLibrary}>
          <WalletProvider>
            <Component {...pageProps} />
          </WalletProvider>
        </Web3ReactProvider>
      </QueryClientProvider>
    </>
  );
}

export default MyApp;
